repos:
  # Python formatting with Black
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=100]

  # Import sorting with isort
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]

  # Custom auto-fix unused imports
  - repo: local
    hooks:
      - id: autofix-imports
        name: Fix unused imports and long lines
        entry: python scripts/autofix_imports.py
        language: python
        types: [python]
        # Optional: only run on modified files for speed
        pass_filenames: true
        require_serial: true
        additional_dependencies: [flake8, black]

  # Python code quality with flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-django]
        args: [--max-line-length=100]
        # Only run on changed files by default
        pass_filenames: true
        verbose: true

  # Format Django HTML templates with djLint
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.3
    hooks:
      - id: djlint-django
        args: [--profile=django, --indent=2, --preserve-blank-lines]
        types_or: [html]
        # Only run on changed files by default
        pass_filenames: true
        verbose: true

  # Format JavaScript and CSS with prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [javascript, css]
        additional_dependencies:
          - prettier@3.2.5

  # Check for trailing whitespace, EOF newlines, debug statements
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']

  # Check for security issues
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["-r", "--skip=B311,B101,B404,B603", "--exclude=tests/,venv/"]
        # Only run on changed files by default
        pass_filenames: true
        verbose: true
