# Generated by Django 5.1.3 on 2024-12-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
