# Generated by Django 5.1.3 on 2024-12-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0002_budgetdeletionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
