# Generated by Django 5.1.3 on 2024-12-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0002_budget_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.CharField(default='PKR', max_length=3),
        ),
    ]
