# Generated by Django 5.1.3 on 2025-03-13 08:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgetapp", "0006_goal_goalcontribution_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goalcontribution",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="goal",
            name="budgetapp_g_user_id_da9968_idx",
        ),
        migrations.RemoveIndex(
            model_name="goal",
            name="budgetapp_g_categor_4ff8df_idx",
        ),
        migrations.RemoveIndex(
            model_name="goal",
            name="budgetapp_g_is_acti_3ae6ef_idx",
        ),
        migrations.RemoveIndex(
            model_name="goalcontribution",
            name="budgetapp_g_goal_id_5f0696_idx",
        ),
        migrations.RemoveIndex(
            model_name="goalcontribution",
            name="budgetapp_g_date_4ab4fc_idx",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="goalcontribution",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="goal",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="budgetapp.category",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="goal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="goalcontribution",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="goalcontribution",
            name="source",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
