# Generated by Django 5.1.3 on 2025-05-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgetapp", "0008_alter_budgetlog_details_alter_goal_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="tag",
            field=models.CharField(
                choices=[
                    ("nayapay", "Nayapay"),
                    ("meezan", "Meezan"),
                    ("cash", "Cash"),
                ],
                default="cash",
                max_length=10,
            ),
        ),
    ]
