# Generated by Django 5.1.3 on 2025-05-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgetapp", "0009_expense_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="tag",
            field=models.CharField(
                choices=[
                    ("nayapay", "Nayapay"),
                    ("meezan", "Meezan"),
                    ("cash", "Cash"),
                    ("none", "None"),
                    ("transferred", "Transferred"),
                ],
                default="meezan",
                max_length=255,
            ),
        ),
    ]
